### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
Make it look like an actual hourglass. This is an early draft and is subject to change. Let me know if you think there are some stuff that could be improved. Once it's final, I'll be pixel fitting them.

### CODE REVIEW

**Comment by ryonakano** [comment]
What does it look like if the color of the glass is not blue and white like the color of the clock face in the old icon?

**Comment by Fatih20** [comment]
> How does it look like if the color of the glass is not blue and white like the color of the clock face in the old icon?
Here's without the blue overlay.
image
Here's with one.
image

**Comment by Fatih20** [comment]
Here's a rework on the idea.
image

**Comment by ryonakano** [comment]
@Fatih20 Hi, thank you for your alternatives! I tried installing each one. Here are how they look like in the desktop:









I personally feel the last one would be the best, because the contrast between the color of the glass and the sand is high and it's easy to see.

**Comment by Fatih20** [comment]
> @Fatih20 Hi, thank you for your alternatives! I tried installing each one. Here are how they look like in the desktop:
> 
> 
> 
> 
> 
> 
> 
> 
> 
> I personally feel the last one would be the best, because the contrast between the color of the glass and the sand is high and it's easy to see.

By the last one you mean the last screenshot here?

I personally think the one I recently sent is the best shape wise, I'll adjust the color if so.

**Comment by ryonakano** [comment]
> By the last one you mean the last screenshot here?

Yes.

**Comment by Fatih20** [comment]
Here's a color-adjusted version of the last one I sent to make the sand contrast the glass.
image

**Comment by Fatih20** [comment]
If this one's good I'll pixel fit it in no time!

**Comment by ryonakano** [comment]
I tested many times, and still love the following one most that you designed:



It really looks like a real hourglass. I wish you would make pixel-fit icons of this version.

**Comment by Fatih20** [comment]
> I tested many times, and still love the following one most that you designed:
> 
> 
> 
> It really looks like a real hourglass. I wish you would make pixel-fit icons of this version.

But what makes it so? If it's the sand pouring from the top, I can add that.

**Comment by ryonakano** [comment]
Hmm, would you add the pouring sand from the top then?

**Comment by Fatih20** [comment]
> Hmm, would you add the pouring sand from the top then?

Sure.

**Comment by Fatih20** [comment]
This is not final, but this is what I've come up with.
image

**Comment by ryonakano** [comment]
This might be nitpicking, but I feel its shape looks like a liquid (like oil), not sand. Although there are some hourglasses that use oil instead of sand, would it be possible to make the shape looks like more sand, e.g. wave the shape like the previous one?

**Comment by Fatih20** [comment]
> This might be nitpicking, but I feel its shape looks like a liquid (like oil), not sand. Although there are some hourglasses that use oil instead of sand, would it be possible to make the shape looks like more sand, e.g. wave the shape like the previous one?

Hmm, you're right. I'll look into it.

**Comment by Fatih20** [comment]
The dripping is less aggressive, the "hill" at the top is flatter, and it follows the shape of the hourglass. like how sand in an hourglass would.
image

**Comment by ryonakano** [comment]
The top looks good now! Would it be possible to make the bottom more sandish? I think the shape of real fallen sand would be a triangle rather than a semicircle:

nathan-dumlao-5Hl5reICevY-unsplash

**Comment by Fatih20** [comment]
You're right it does. I'll be tweaking the top a bit to smooth the sharp edges and then fix the bottom.

**Comment by Fatih20** [comment]
What do you think of this?
image

**Comment by ryonakano** [comment]
I think this design is good!

**Comment by Fatih20** [comment]
Before I'm pixel fitting them, please try it and let me know if there is ANY thing that doesn't sit right with you. Nitpick all you want, it's better to have it the best I can make than having regrets down the road.

**Comment by ryonakano** [comment]
@Fatih20 I've been using the app with the new icon for a couple of days and it really looks nice for me! :tada: I have no more opinions.

@sgpthomas Any opinions from you?

**Comment by ryonakano** [comment]
Hi @Fatih20, sorry for the late action, but I'd like your icon to be the new app icon!

Would you make the new icon in other pixels (16, 24, 32, 48, 64, and 128px) based on the latest  `data/com.github.sgpthomas.hourglass.svg` in your branch? If that complete I guess we're ready to merge this PR.

**Comment by Fatih20** [comment]
> Hi @Fatih20, sorry for the late action, but I'd like your icon to be the new app icon!
> 
> Would you make the new icon in other pixels (16, 24, 32, 48, 64, and 128px) based on the latest `data/com.github.sgpthomas.hourglass.svg` in your branch? If that complete I guess we're ready to merge this PR.

I'll start work on those.

**Comment by Fatih20** [comment]
Sorry that this took so long! Please build the app first and see if there's any issue with the icons at smaller sizes before pushing. Be sure to quickly tell me any issue that you come across.

**Review by ryonakano — APPROVED** [review]
Really looks sweet, thank you very much for your work! No issues found.

If you are OK I'll merge this branch.

**Comment by Fatih20** [comment]
> Really looks sweet, thank you very much for your work! No issues found.
> 
> If you are OK I'll merge this branch.

Great, go ahead.

**Pull request merged**
