### PR TITLE
Add meson

### PR DESCRIPTION
**Pull request by ryonakano**
Supersedes #53
It seems like the previous PR was wrong and causes some issues like #56.

## Changes Summary
- Add Meson build system
- Make metadata files (`.appdata.xml` and `.desktop` files) translatable
- Complete RDNN

## TODO (in other PRs)
- Fix deprecations like Granite.Application
- Update Debian packaging to use Meson
- Remove CMake files

This PR is ready for review/merge.

### CODE REVIEW

**Comment by ryonakano** [comment]
@sgpthomas I would appreciate it if you could review/merge this PR :)

**Comment by sgpthomas** [comment]
Can you add instructions to the README on how to build the project using meson?

**Comment by sgpthomas** [comment]
It seems to build for me but it crashes before it starts.
```
[INFO 14:01:44.947135] Application.vala:156: Hourglass version: 1.1.1
[INFO 14:01:44.947202] Application.vala:158: Kernel version: 5.6.3-300.fc32.x86_64
[DEBUG 14:01:44.947346] Settings.vala:163: Loading settings from schema 'com.github.sgpthomas.hourglass.saved'
[DEBUG 14:01:44.947699] Settings.vala:163: Loading settings from schema 'org.gnome.desktop.interface'
[INFO 14:01:44.947839] Hourglass.vala:98: starting daemon
[DEBUG 14:01:44.947893] [GLib] posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested) 
[FATAL 14:01:44.951138] file ../src/Services/DBusManager.vala: line 46: unexpected error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (g-dbus-error-quark, 2)
[DEBUG 14:01:44.952497] [GLib] unsetenv() is not thread-safe and should not be used after threads are created
[ERROR 14:01:44.954415] StyleManager.vala:33: Error with stylesheet: <broken file>:1:0Failed to import: Error opening file /home/samthomas/Development/hourglass/build/share/com.github.sgpthomas.hourglass/style/text.css: No such file or directory
** Message: 14:01:44.968: HourglassDaemon.vala:39: Hourglass-Daemon started
** Message: 14:01:44.968: AlarmManager.vala:28: Initiating Alarm Manager

** (process:57790): CRITICAL **: 14:01:44.968: hourglass_daemon_saved_alarms_get_alarms: assertion 'self != NULL' failed
** Message: 14:01:44.971: HourglassDaemon.vala:63: Daemon Activated
** Message: 14:01:44.971: HourglassServer.vala:77: com.github.sgpthomas.hourglass was successfully registered!
[1]    57784 trace trap (core dumped)  ./com.github.sgpthomas.hourglass
```
I am running on Fedora 32 though, and not elementary. Does this happen for you?

**Comment by ryonakano** [comment]
> It seems to build for me but it crashes before it starts.
> 
> ```
> [INFO 14:01:44.947135] Application.vala:156: Hourglass version: 1.1.1
> [INFO 14:01:44.947202] Application.vala:158: Kernel version: 5.6.3-300.fc32.x86_64
> [DEBUG 14:01:44.947346] Settings.vala:163: Loading settings from schema 'com.github.sgpthomas.hourglass.saved'
> [DEBUG 14:01:44.947699] Settings.vala:163: Loading settings from schema 'org.gnome.desktop.interface'
> [INFO 14:01:44.947839] Hourglass.vala:98: starting daemon
> [DEBUG 14:01:44.947893] [GLib] posix_spawn avoided (automatic reaping requested) (workdir specified) (fd close requested) 
> [FATAL 14:01:44.951138] file ../src/Services/DBusManager.vala: line 46: unexpected error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (g-dbus-error-quark, 2)
> [DEBUG 14:01:44.952497] [GLib] unsetenv() is not thread-safe and should not be used after threads are created
> [ERROR 14:01:44.954415] StyleManager.vala:33: Error with stylesheet: <broken file>:1:0Failed to import: Error opening file /home/samthomas/Development/hourglass/build/share/com.github.sgpthomas.hourglass/style/text.css: No such file or directory
> ** Message: 14:01:44.968: HourglassDaemon.vala:39: Hourglass-Daemon started
> ** Message: 14:01:44.968: AlarmManager.vala:28: Initiating Alarm Manager
> 
> ** (process:57790): CRITICAL **: 14:01:44.968: hourglass_daemon_saved_alarms_get_alarms: assertion 'self != NULL' failed
> ** Message: 14:01:44.971: HourglassDaemon.vala:63: Daemon Activated
> ** Message: 14:01:44.971: HourglassServer.vala:77: com.github.sgpthomas.hourglass was successfully registered!
> [1]    57784 trace trap (core dumped)  ./com.github.sgpthomas.hourglass
> ```
> 
> I am running on Fedora 32 though, and not elementary. Does this happen for you?

Yes, this segfault happens to me too. I guess it is because of the way we specify the path to CSS. Running the app by `com.github.sgpthomas.hourglass`, not `./build/com.github.sgpthomas.hourglass` should launch the app successfully.
Providing the CSS by using GResource should make it possible to launch the app by `./build/com.github.sgpthomas.hourglass` too.

**Comment by ryonakano** [comment]
@sgpthomas Should be good now.

**Comment by sgpthomas** [comment]
Awesome! Looks good :)

**Pull request merged**
