### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by NathanBnm**
Here is an update for missing French translations :smile:

### CODE REVIEW

**Review by ryonakano — COMMENTED** [review]
Hi, thanks again Nathan!

Would you update your translation based on `dev` branch? I use `dev` for usual development and `master` just for releasing a new version. I'm working on releasing a big update for the next release, so there should be some additional new source string in `dev`.

**Comment by ryonakano** [comment]
I updated the base branch of your branch, so just run the following command:

```
git checkout update-fr
git pull origin update-fr
cd build
ninja com.github.sgpthomas.hourglass-update-po
ninja extra-po
```

and then re-update your translation. Thanks!

**Comment by NathanBnm** [comment]
@ryonakano thanks I made the changes!

**Review by ryonakano — APPROVED** [review]
It works, thank you!

**Pull request merged**
